# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: scraper

on:
  schedule:
  - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest

    env:
      WB_URL: https://s.weibo.com/top/summary?cate=realtimehot
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.16'
    - name: Install Dependencies
      run: npm ci
    - name: Install playwright browsers
      run: npx playwright install --with-deps
    - name: Run scraper
      env:
        DATABASE_URL: ${{ secrets.DATABASE_URL }}
      run: npm start
